CREATE TABLE TB_PESSOA (
  CODIGO_PESSOA NUMBER(9) NOT NULL,
  NOME          VARCHAR2(256) NOT NULL,
  SOBRENOME     VARCHAR2(256) NOT NULL,
  IDADE         NUMBER(3) NOT NULL,
  LOGIN         VARCHAR2(50) NOT NULL,
  SENHA         VARCHAR2(50) NOT NULL,
  STATUS        NUMBER(3) NOT NULL,
  CONSTRAINT TB_PESSOA_PK PRIMARY KEY (CODIGO_PESSOA) ENABLE
);
