CREATE TABLE TB_MUNICIPIO (
  CODIGO_MUNICIPIO NUMBER(9) NOT NULL,
  CODIGO_UF        NUMBER(9) NOT NULL,
  NOME             VARCHAR2(256),
  STATUS           NUMBER(3),
  CONSTRAINT TB_MUNICIPIO_PK PRIMARY KEY (CODIGO_MUNICIPIO) ENABLE
);
