CREATE TABLE TB_BAIRRO (
  CODIGO_BAIRRO    NUMBER(9) NOT NULL,
  CODIGO_MUNICIPIO NUMBER(9) NOT NULL,
  NOME             VARCHAR2(256) NOT NULL,
  STATUS           NUMBER(3),
  CONSTRAINT TB_BAIRRO_PK PRIMARY KEY (CODIGO_BAIRRO) ENABLE
);
