CREATE TABLE TB_ENDERECO (
  CODIGO_ENDERECO NUMBER(9) NOT NULL,
  CODIGO_PESSOA   NUMBER(9) NOT NULL,
  CODIGO_BAIRRO   NUMBER(9) NOT NULL,
  NOME_RUA        VARCHAR2(256) NOT NULL,
  NUMERO          VARCHAR2(10) NOT NULL,
  COMPLEMENTO     VARCHAR2(20),
  CEP             VARCHAR2(10) NOT NULL,
  CONSTRAINT TB_ENDERECO_PK PRIMARY KEY (CODIGO_ENDERECO) ENABLE
);
