ALTER TABLE TB_BAIRRO
ADD CONSTRAINT TB_BAIRRO_FK1 FOREIGN KEY (CODIGO_MUNICIPIO)
REFERENCES TB_MUNICIPIO (CODIGO_MUNICIPIO ) ENABLE;

ALTER TABLE TB_ENDERECO
ADD CONSTRAINT TB_ENDERECO_FK1 FOREIGN KEY (CODIGO_PESSOA)
REFERENCES TB_PESSOA (CODIGO_PESSOA ) ENABLE;

ALTER TABLE TB_ENDERECO
ADD CONSTRAINT TB_ENDERECO_FK2 FOREIGN KEY (CODIGO_BAIRRO)
REFERENCES TB_BAIRRO (CODIGO_BAIRRO) ENABLE;

ALTER TABLE TB_MUNICIPIO
ADD CONSTRAINT TB_MUNICIPIO_FK1 FOREIGN KEY (CODIGO_UF)
REFERENCES TB_UF (CODIGO_UF) ENABLE;
