COMMENT ON COLUMN TB_UF.STATUS IS '1 - ATIVADO 2 - DESATIVADO';

COMMENT ON COLUMN TB_MUNICIPIO.STATUS IS '1 - ATIVADO 2 - DESATIVADO';

COMMENT ON COLUMN TB_BAIRRO.STATUS IS '1- ATIVADO 2- DESATIVADO';

COMMENT ON COLUMN TB_PESSOA.STATUS IS '1 - ATIVADO 2 - DESATIVADO';