CREATE SEQUENCE SEQUENCE_PESSOA INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 NOCACHE;

CREATE SEQUENCE SEQUENCE_ENDERECO INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 NOCACHE;

CREATE SEQUENCE SEQUENCE_BAIRRO INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 NOCACHE;

CREATE SEQUENCE SEQUENCE_MUNICIPIO INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 NOCACHE;

CREATE SEQUENCE SEQUENCE_UF INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 NOCACHE;

ALTER TABLE TB_PESSOA MODIFY CODIGO_PESSOA NUMBER(9) DEFAULT SEQUENCE_PESSOA.NEXTVAL;

ALTER TABLE TB_UF MODIFY CODIGO_UF NUMBER(9) DEFAULT SEQUENCE_UF.NEXTVAL;

ALTER TABLE TB_MUNICIPIO MODIFY CODIGO_MUNICIPIO NUMBER(9) DEFAULT SEQUENCE_MUNICIPIO.NEXTVAL;

ALTER TABLE TB_BAIRRO MODIFY CODIGO_BAIRRO NUMBER(9) DEFAULT SEQUENCE_BAIRRO.NEXTVAL;

ALTER TABLE TB_ENDERECO MODIFY CODIGO_ENDERECO NUMBER(9) DEFAULT SEQUENCE_ENDERECO.NEXTVAL;
