-- UF

INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('AC', 'Acre', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('AL', 'Alagoas', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('AP', 'Amapá', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('AM', 'Amazonas', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('BA', 'Bahia', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('CE', 'Ceará', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('DF', 'Distrito Federal', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('ES', 'Espírito Santo', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('GO', 'Goiás', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('MA', 'Maranhão', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('MT', 'Mato Grosso', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('MS', 'Mato Grosso do Sul', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('MG', 'Minas Gerais', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('PA', 'Pará', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('PB', 'Paraíba', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('PR', 'Paraná', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('PE', 'Pernambuco', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('PI', 'Piauí', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('RJ', 'Rio de Janeiro', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('RN', 'Rio Grande do Norte', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('RS', 'Rio Grande do Sul', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('RO', 'Rondônia', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('RR', 'Roraima', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('SC', 'Santa Catarina', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('SP', 'São Paulo', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('SE', 'Sergipe', 1);
INSERT INTO TB_UF (SIGLA, NOME, STATUS) VALUES ('TO', 'Tocantins', 1);

-- MUNICIPIOS

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (1, 'Rio Branco', 1);  -- Acre
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (1, 'Cruzeiro do Sul', 1);  -- Acre

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (2, 'Maceió', 1);  -- Alagoas
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (2, 'Arapiraca', 1);  -- Alagoas

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (3, 'Macapá', 1);  -- Amapá
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (3, 'Santana', 1);  -- Amapá

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (4, 'Manaus', 1);  -- Amazonas
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (4, 'Parintins', 1);  -- Amazonas

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (5, 'Salvador', 1);  -- Bahia
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (5, 'Feira de Santana', 1);  -- Bahia

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (6, 'Fortaleza', 1);  -- Ceará
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (6, 'Caucaia', 1);  -- Ceará

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (7, 'Brasília', 1);  -- Distrito Federal
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (7, 'Taguatinga', 1);  -- Distrito Federal

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (8, 'Vitória', 1);  -- Espírito Santo
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (8, 'Vila Velha', 1);  -- Espírito Santo

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (9, 'Goiânia', 1);  -- Goiás
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (9, 'Aparecida de Goiânia', 1);  -- Goiás

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (10, 'São Luís', 1);  -- Maranhão
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (10, 'Imperatriz', 1);  -- Maranhão

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (11, 'Cuiabá', 1);  -- Mato Grosso
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (11, 'Várzea Grande', 1);  -- Mato Grosso

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (12, 'Campo Grande', 1);  -- Mato Grosso do Sul
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (12, 'Dourados', 1);  -- Mato Grosso do Sul

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (13, 'Belo Horizonte', 1);  -- Minas Gerais
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (13, 'Uberlândia', 1);  -- Minas Gerais

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (14, 'Belém', 1);  -- Pará
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (14, 'Ananindeua', 1);  -- Pará

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (15, 'João Pessoa', 1);  -- Paraíba
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (15, 'Campina Grande', 1);  -- Paraíba

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (16, 'Curitiba', 1);  -- Paraná
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (16, 'Londrina', 1);  -- Paraná

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (17, 'Recife', 1);  -- Pernambuco
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (17, 'Olinda', 1);  -- Pernambuco

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (18, 'Teresina', 1);  -- Piauí
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (18, 'Parnaíba', 1);  -- Piauí

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (19, 'Rio de Janeiro', 1);  -- Rio de Janeiro
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (19, 'Niterói', 1);  -- Rio de Janeiro

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (20, 'Natal', 1);  -- Rio Grande do Norte
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (20, 'Mossoró', 1);  -- Rio Grande do Norte

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (21, 'Porto Alegre', 1);  -- Rio Grande do Sul
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (21, 'Canoas', 1);  -- Rio Grande do Sul

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (22, 'Porto Velho', 1);  -- Rondônia
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (22, 'Ji-Paraná', 1);  -- Rondônia

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (23, 'Boa Vista', 1);  -- Roraima
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (23, 'Rorainópolis', 1);  -- Roraima

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (24, 'Florianópolis', 1);  -- Santa Catarina
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (24, 'Joinville', 1);  -- Santa Catarina

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (25, 'São Paulo', 1);  -- São Paulo
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (25, 'Campinas', 1);  -- São Paulo

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (26, 'Aracaju', 1);  -- Sergipe
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (26, 'Lagarto', 1);  -- Sergipe

INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (27, 'Palmas', 1);  -- Tocantins
INSERT INTO TB_MUNICIPIO (CODIGO_UF, NOME, STATUS) VALUES (27, 'Araguaina', 1);  -- Tocantins

-- BAIRRO

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (1, 'Centro', 1);  -- Rio Branco, Acre
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (1, 'Bairro da Paz', 1);  -- Rio Branco, Acre

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (3, 'Ponta Verde', 1);  -- Maceió, Alagoas
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (3, 'Pajuçara', 1);  -- Maceió, Alagoas

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (5, 'Central', 1);  -- Macapá, Amapá
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (5, 'São Lázaro', 1);  -- Macapá, Amapá

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (7, 'Centro', 1);  -- Manaus, Amazonas
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (7, 'Adrianópolis', 1);  -- Manaus, Amazonas

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (9, 'Pelourinho', 1);  -- Salvador, Bahia
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (9, 'Barra', 1);  -- Salvador, Bahia

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (11, 'Aldeota', 1);  -- Fortaleza, Ceará
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (11, 'Meireles', 1);  -- Fortaleza, Ceará

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (13, 'Asa Sul', 1);  -- Brasília, DF
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (13, 'Taguatinga Centro', 1);  -- Brasília, DF

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (15, 'Praia do Canto', 1);  -- Vitória, Espírito Santo
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (15, 'Jardim da Penha', 1);  -- Vitória, Espírito Santo

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (17, 'Setor Bueno', 1);  -- Goiânia, Goiás
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (17, 'Jardim Goiás', 1);  -- Goiânia, Goiás

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (19, 'Centro', 1);  -- São Luís, Maranhão
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (19, 'Cohab', 1);  -- São Luís, Maranhão

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (21, 'Centro', 1);  -- Cuiabá, Mato Grosso
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (21, 'CPA I', 1);  -- Cuiabá, Mato Grosso

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (23, 'Centro', 1);  -- Campo Grande, Mato Grosso do Sul
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (23, 'Jardim dos Estados', 1);  -- Campo Grande, Mato Grosso do Sul

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (25, 'Savassi', 1);  -- Belo Horizonte, Minas Gerais
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (25, 'Funcionários', 1);  -- Belo Horizonte, Minas Gerais

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (27, 'Marco', 1);  -- Belém, Pará
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (27, 'São Braz', 1);  -- Belém, Pará

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (29, 'Torre', 1);  -- João Pessoa, Paraíba
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (29, 'Bessa', 1);  -- João Pessoa, Paraíba

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (31, 'Centro', 1);  -- Curitiba, Paraná
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (31, 'Batel', 1);  -- Curitiba, Paraná

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (33, 'Boa Viagem', 1);  -- Recife, Pernambuco
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (33, 'Olinda', 1);  -- Olinda, Pernambuco

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (35, 'Centro', 1);  -- Teresina, Piauí
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (35, 'São Cristóvão', 1);  -- Teresina, Piauí

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (37, 'Copacabana', 1);  -- Rio de Janeiro, Rio de Janeiro
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (37, 'Ipanema', 1);  -- Rio de Janeiro, Rio de Janeiro

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (39, 'Ponta Negra', 1);  -- Natal, Rio Grande do Norte
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (39, 'Alecrim', 1);  -- Natal, Rio Grande do Norte

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (41, 'Centro', 1);  -- Porto Alegre, Rio Grande do Sul
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (41, 'Moinhos de Vento', 1);  -- Porto Alegre, Rio Grande do Sul

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (43, 'Centro', 1);  -- Porto Velho, Rondônia
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (43, 'Jardim Eldorado', 1);  -- Porto Velho, Rondônia

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (45, 'Centro', 1);  -- Boa Vista, Roraima
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (45, 'Buritis', 1);  -- Boa Vista, Roraima

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (47, 'Centro', 1);  -- Florianópolis, Santa Catarina
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (47, 'Trindade', 1);  -- Florianópolis, Santa Catarina

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (49, 'Centro', 1);  -- São Paulo, São Paulo
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (49, 'Jardins', 1);  -- São Paulo, São Paulo

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (51, 'Centro', 1);  -- Aracaju, Sergipe
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (51, 'Atalaia', 1);  -- Aracaju, Sergipe

INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (53, 'Centro', 1);  -- Palmas, Tocantins
INSERT INTO TB_BAIRRO (CODIGO_MUNICIPIO, NOME, STATUS) VALUES (53, 'Plano Diretor', 1);  -- Palmas, Tocantins

-- PESSOA

INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('João', 'da Silva', 39, 'joaodasilva', 'senha123', 1);  -- Ativado
INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Maria', 'Oliveira', 34, 'mariaoliveira', 'senha123', 1);  -- Ativado

INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Carlos', 'Pereira', 36, 'carlospereira', 'senha123', 1);  -- Ativado
INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Ana', 'Santos', 31, 'anasantos', 'senha123', 1);  -- Ativado

INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Luiz', 'Costa', 45, 'luizcosta', 'senha123', 1);  -- Ativado
INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Juliana', 'Almeida', 29, 'julianaalmeida', 'senha123', 1);  -- Ativado

INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Fernando', 'Lima', 42, 'fernandolima', 'senha123', 1);  -- Ativado
INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Patrícia', 'Gomes', 26, 'patriciagomes', 'senha123', 1);  -- Ativado

INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Roberto', 'Sousa', 38, 'robertosousa', 'senha123', 1);  -- Ativado
INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Sofia', 'Martins', 24, 'sofiamartins', 'senha123', 1);  -- Ativado

INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Eduardo', 'Silva', 33, 'eduardosilva', 'senha123', 1);  -- Ativado
INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Fernanda', 'Lima', 28, 'fernandalima', 'senha123', 1);  -- Ativado

INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Gabriel', 'Costa', 40, 'gabrielcosta', 'senha123', 1);  -- Ativado
INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Cláudia', 'Santos', 30, 'claudiasantos', 'senha123', 1);  -- Ativado

INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Hugo', 'Almeida', 37, 'hugolmeida', 'senha123', 1);  -- Ativado
INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Tatiane', 'Ferreira', 27, 'tatianferreira', 'senha123', 1);  -- Ativado

INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Lucas', 'Rodrigues', 35, 'lucasrodrigues', 'senha123', 1);  -- Ativado
INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Rafaela', 'Almeida', 22, 'rafaelaalmeida', 'senha123', 1);  -- Ativado

INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('André', 'Santos', 39, 'andresantos', 'senha123', 1);  -- Ativado
INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Juliana', 'Pires', 25, 'julianapires', 'senha123', 1);  -- Ativado

INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Fabiano', 'Costa', 44, 'fabianocosta', 'senha123', 1);  -- Ativado
INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Natalia', 'Silva', 32, 'nataliasilva', 'senha123', 1);  -- Ativado

INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Diego', 'Lima', 29, 'diegolima', 'senha123', 1);  -- Ativado
INSERT INTO TB_PESSOA (NOME, SOBRENOME, IDADE, LOGIN, SENHA, STATUS) VALUES ('Bianca', 'Martins', 21, 'biancamartins', 'senha123', 1);  -- Ativado

-- ENDERECO

INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (1, 1, 'Rua A', '123', 'Apto 1', '12345-678');  -- João da Silva
INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (1, 2, 'Rua B', '456', 'Casa', '12345-679');  -- João da Silva

INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (2, 3, 'Rua C', '789', 'Apto 2', '12345-680');  -- Maria Oliveira

INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (3, 1, 'Rua D', '321', NULL, '12345-681');  -- Carlos Pereira
INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (4, 2, 'Rua E', '654', 'Sala 3', '12345-682');  -- Ana Santos

INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (5, 1, 'Rua F', '987', NULL, '12345-683');  -- Luiz Costa
INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (6, 2, 'Rua G', '246', 'Bloco A', '12345-684');  -- Juliana Almeida

INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (7, 1, 'Rua H', '135', NULL, '12345-685');  -- Fernando Lima
INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (8, 2, 'Rua I', '246', 'Casa 4', '12345-686');  -- Patrícia Gomes

INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (9, 1, 'Rua J', '369', NULL, '12345-687');  -- Roberto Sousa
INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (10, 2, 'Rua K', '258', NULL, '12345-688');  -- Sofia Martins

INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (11, 1, 'Rua L', '147', NULL, '12345-689');  -- Eduardo Silva
INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (12, 2, 'Rua M', '258', 'Sala 5', '12345-690');  -- Fernanda Lima

INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (13, 1, 'Rua N', '369', NULL, '12345-691');  -- Gabriel Costa
INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (14, 2, 'Rua O', '159', 'Casa 6', '12345-692');  -- Cláudia Santos

INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (15, 1, 'Rua P', '753', NULL, '12345-693');  -- Hugo Almeida
INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (16, 2, 'Rua Q', '951', NULL, '12345-694');  -- Tatiane Ferreira

INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (17, 1, 'Rua R', '258', NULL, '12345-695');  -- Lucas Rodrigues
INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (18, 2, 'Rua S', '369', NULL, '12345-696');  -- Rafaela Almeida

INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (19, 1, 'Rua T', '147', NULL, '12345-697');  -- André Santos
INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (20, 2, 'Rua U', '258', NULL, '12345-698');  -- Juliana Pires

INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (21, 1, 'Rua V', '369', NULL, '12345-699');  -- Fabiano Costa
INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (22, 2, 'Rua W', '147', NULL, '12345-700');  -- Natalia Silva

INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (23, 1, 'Rua X', '258', NULL, '12345-701');  -- Diego Lima
INSERT INTO TB_ENDERECO (CODIGO_PESSOA, CODIGO_BAIRRO, NOME_RUA, NUMERO, COMPLEMENTO, CEP) VALUES (24, 2, 'Rua Y', '369', NULL, '12345-702');  -- Bianca Martins

